import { formatPKR, formatDate } from '@/lib/utils';

export function openPrintWindow(html: string, title: string) {
  const win = window.open('', '_blank', 'width=800,height=600');
  if (win) {
    win.document.write(html);
    win.document.close();
    setTimeout(() => { win.print(); }, 300);
  }
}

export function generateSaleInvoice(sale: any, shopName: string, shopType: string) {
  const invoiceNo = `INV-${(sale._id || '').slice(0, 8).toUpperCase()}`;
  const date = formatDate(sale.date);
  const customer = sale.isWalkIn ? 'Walk-in Customer' : sale.customerId?.name || 'Customer';

  const itemRows = (sale.items || []).map((item: any, i: number) => `
    <tr>
      <td style="padding:10px 16px;border-bottom:1px solid #f3f4f6;font-size:13px">${i + 1}</td>
      <td style="padding:10px 16px;border-bottom:1px solid #f3f4f6;font-size:13px;font-weight:500">${item.productId?.name || '-'}</td>
      <td style="padding:10px 16px;border-bottom:1px solid #f3f4f6;font-size:13px;text-align:center">${item.qty}</td>
      <td style="padding:10px 16px;border-bottom:1px solid #f3f4f6;font-size:13px;text-align:right">${formatPKR(item.unitPrice)}</td>
      <td style="padding:10px 16px;border-bottom:1px solid #f3f4f6;font-size:13px;text-align:right;font-weight:600">${formatPKR(item.total)}</td>
    </tr>
  `).join('');

  return `<!DOCTYPE html><html><head><title>Invoice ${invoiceNo}</title><style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #1f2937; padding: 40px; max-width: 700px; margin: 0 auto; }
    .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 32px; }
    .shop-name { font-size: 24px; font-weight: 700; color: #16a34a; }
    .shop-type { font-size: 12px; color: #6b7280; margin-top: 2px; }
    .invoice-badge { background: #16a34a; color: white; padding: 6px 16px; border-radius: 6px; font-size: 12px; font-weight: 600; }
    .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; margin-bottom: 28px; padding: 16px; background: #f9fafb; border-radius: 8px; }
    .info-label { font-size: 11px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 2px; }
    .info-value { font-size: 14px; font-weight: 500; color: #1f2937; }
    table { width: 100%; border-collapse: collapse; }
    th { background: #f9fafb; padding: 10px 16px; text-align: left; font-size: 11px; font-weight: 600; color: #6b7280; text-transform: uppercase; letter-spacing: 0.05em; border-bottom: 1px solid #e5e7eb; }
    .totals { margin-top: 16px; padding: 16px; background: #f9fafb; border-radius: 8px; }
    .total-row { display: flex; justify-content: space-between; padding: 6px 0; font-size: 14px; }
    .total-row.grand { font-size: 18px; font-weight: 700; color: #16a34a; border-top: 2px solid #16a34a; padding-top: 10px; margin-top: 6px; }
    .total-row.due { color: #dc2626; font-weight: 600; }
    .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e5e7eb; font-size: 11px; color: #9ca3af; text-align: center; }
    @media print { body { padding: 20px; } }
  </style></head><body>
    <div class="header">
      <div><div class="shop-name">${shopName}</div><div class="shop-type">${shopType}</div></div>
      <div class="invoice-badge">INVOICE</div>
    </div>
    <div class="info-grid">
      <div><div class="info-label">Invoice No</div><div class="info-value">${invoiceNo}</div></div>
      <div><div class="info-label">Date</div><div class="info-value">${date}</div></div>
      <div><div class="info-label">Customer</div><div class="info-value">${customer}</div></div>
      <div><div class="info-label">Status</div><div class="info-value" style="color:${sale.dueAmount > 0 ? '#dc2626' : '#16a34a'}">${sale.dueAmount > 0 ? 'Partial / Due' : 'Paid'}</div></div>
    </div>
    <table>
      <thead><tr><th>#</th><th>Item</th><th style="text-align:center">Qty</th><th style="text-align:right">Unit Price</th><th style="text-align:right">Total</th></tr></thead>
      <tbody>${itemRows}</tbody>
    </table>
    <div class="totals">
      <div class="total-row"><span>Total Amount</span><span>${formatPKR(sale.totalAmount)}</span></div>
      <div class="total-row"><span>Received</span><span style="color:#16a34a">${formatPKR(sale.receivedAmount)}</span></div>
      ${sale.dueAmount > 0 ? `<div class="total-row due"><span>Due Amount</span><span>${formatPKR(sale.dueAmount)}</span></div>` : ''}
    </div>
    ${sale.notes ? `<div style="margin-top:20px;padding:12px;background:#fffbeb;border-radius:6px;font-size:12px;color:#92400e"><strong>Notes:</strong> ${sale.notes}</div>` : ''}
    <div class="footer">Thank you for your business! &bull; ${shopName} &bull; Generated by BizManager</div>
  </body></html>`;
}

export function generatePaymentReceipt(payment: any, shopName: string, shopType: string, customerName?: string) {
  const receiptNo = `RCT-${(payment._id || '').slice(0, 8).toUpperCase()}`;
  const date = formatDate(payment.date);
  const party = customerName || payment.partyId?.name || 'N/A';

  return `<!DOCTYPE html><html><head><title>Receipt ${receiptNo}</title><style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #1f2937; padding: 40px; max-width: 600px; margin: 0 auto; }
    .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 32px; }
    .shop-name { font-size: 24px; font-weight: 700; color: #16a34a; }
    .shop-type { font-size: 12px; color: #6b7280; margin-top: 2px; }
    .receipt-badge { background: #2563eb; color: white; padding: 6px 16px; border-radius: 6px; font-size: 12px; font-weight: 600; }
    .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; margin-bottom: 28px; padding: 16px; background: #f9fafb; border-radius: 8px; }
    .info-label { font-size: 11px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 2px; }
    .info-value { font-size: 14px; font-weight: 500; color: #1f2937; }
    .amount-box { margin-top: 24px; padding: 24px; background: #f0fdf4; border-radius: 8px; text-align: center; border: 2px solid #bbf7d0; }
    .amount-label { font-size: 12px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 4px; }
    .amount-value { font-size: 32px; font-weight: 700; color: #16a34a; }
    .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e5e7eb; font-size: 11px; color: #9ca3af; text-align: center; }
    @media print { body { padding: 20px; } }
  </style></head><body>
    <div class="header">
      <div><div class="shop-name">${shopName}</div><div class="shop-type">${shopType}</div></div>
      <div class="receipt-badge">RECEIPT</div>
    </div>
    <div class="info-grid">
      <div><div class="info-label">Receipt No</div><div class="info-value">${receiptNo}</div></div>
      <div><div class="info-label">Date</div><div class="info-value">${date}</div></div>
      <div><div class="info-label">Received From</div><div class="info-value">${party}</div></div>
      <div><div class="info-label">Payment Method</div><div class="info-value" style="text-transform:capitalize">${payment.method || 'cash'}</div></div>
      ${payment.referenceType === 'sale' ? `<div><div class="info-label">Reference</div><div class="info-value">Sale #${(payment.referenceId || '').slice(0, 8).toUpperCase()}</div></div>` : ''}
    </div>
    <div class="amount-box">
      <div class="amount-label">Amount Received</div>
      <div class="amount-value">${formatPKR(payment.amount)}</div>
    </div>
    ${payment.notes ? `<div style="margin-top:20px;padding:12px;background:#fffbeb;border-radius:6px;font-size:12px;color:#92400e"><strong>Notes:</strong> ${payment.notes}</div>` : ''}
    <div class="footer">Payment receipt &bull; ${shopName} &bull; Generated by BizManager</div>
  </body></html>`;
}

export function generateCustomerLedger(customer: any, entries: any[], shopName: string, shopType: string) {
  const date = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });

  const entryRows = entries.map((e: any) => `
    <tr>
      <td style="padding:8px 16px;border-bottom:1px solid #f3f4f6;font-size:12px">${formatDate(e.date)}</td>
      <td style="padding:8px 16px;border-bottom:1px solid #f3f4f6;font-size:12px">${e.desc}</td>
      <td style="padding:8px 16px;border-bottom:1px solid #f3f4f6;font-size:12px;text-align:right">${e.debit ? formatPKR(e.debit) : '-'}</td>
      <td style="padding:8px 16px;border-bottom:1px solid #f3f4f6;font-size:12px;text-align:right">${e.credit ? formatPKR(e.credit) : '-'}</td>
      <td style="padding:8px 16px;border-bottom:1px solid #f3f4f6;font-size:12px;text-align:right;font-weight:600;color:${e.balance > 0 ? '#dc2626' : '#16a34a'}">${formatPKR(e.balance)}</td>
    </tr>
  `).join('');

  return `<!DOCTYPE html><html><head><title>Ledger - ${customer.name}</title><style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #1f2937; padding: 40px; max-width: 700px; margin: 0 auto; }
    .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 32px; border-bottom: 2px solid #16a34a; padding-bottom: 16px; }
    .shop-name { font-size: 22px; font-weight: 700; color: #16a34a; }
    .shop-type { font-size: 12px; color: #6b7280; margin-top: 2px; }
    .meta { text-align: right; font-size: 12px; color: #6b7280; }
    .customer-info { margin-bottom: 24px; padding: 16px; background: #f9fafb; border-radius: 8px; }
    .customer-name { font-size: 18px; font-weight: 600; color: #1f2937; }
    .customer-detail { font-size: 12px; color: #6b7280; margin-top: 4px; }
    .due-box { margin-top: 12px; padding: 10px 16px; background: ${customer.totalDue > 0 ? '#fef2f2' : '#f0fdf4'}; border-radius: 6px; display: flex; justify-content: space-between; }
    .due-label { font-weight: 600; font-size: 13px; }
    .due-value { font-weight: 700; font-size: 13px; color: ${customer.totalDue > 0 ? '#dc2626' : '#16a34a'}; }
    table { width: 100%; border-collapse: collapse; }
    th { background: #f9fafb; padding: 10px 16px; text-align: left; font-size: 11px; font-weight: 600; color: #6b7280; text-transform: uppercase; letter-spacing: 0.05em; border-bottom: 1px solid #e5e7eb; }
    .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e5e7eb; font-size: 11px; color: #9ca3af; text-align: center; }
    @media print { body { padding: 20px; } }
  </style></head><body>
    <div class="header">
      <div><div class="shop-name">${shopName}</div><div class="shop-type">${shopType}</div></div>
      <div class="meta"><div>Generated: ${date}</div><div>Customer Ledger</div></div>
    </div>
    <div class="customer-info">
      <div class="customer-name">${customer.name}</div>
      ${customer.phone ? `<div class="customer-detail">Phone: ${customer.phone}</div>` : ''}
      ${customer.address ? `<div class="customer-detail">Address: ${customer.address}</div>` : ''}
      <div class="due-box">
        <span class="due-label">Current Balance Due</span>
        <span class="due-value">${formatPKR(customer.totalDue)}</span>
      </div>
    </div>
    <table>
      <thead><tr><th>Date</th><th>Description</th><th style="text-align:right">Debit</th><th style="text-align:right">Credit</th><th style="text-align:right">Balance</th></tr></thead>
      <tbody>${entryRows || '<tr><td colspan="5" style="text-align:center;color:#9ca3af;padding:24px">No transactions</td></tr>'}</tbody>
    </table>
    <div class="footer">Customer Ledger &bull; ${shopName} &bull; Generated by BizManager</div>
  </body></html>`;
}
